"""TMC Codes
The Traffic Message Channel (TMC) Codes are used as basic information on traffic distortions or warnings.
These codes give Natural Language descriptions of the traffic accident data.

https://wiki.openstreetmap.org/wiki/TMC/Event_Code_List
"""


'''TMC Codes Listing
This constant listing gives a description for the TMC code corresponding to its index.
Since there is no TMC Code 0, the first element has been set to NaN.
'''
TMC_CODES = ['NaN',
             'heavy lorries are recommended to avoid the area',
             'follow signs', 
             'follow diversion signs', 
             'diversion in operation', 
             'no suitable diversion available', 
             'diversion is no longer recommended', 
             'for exceptional loads only', 
             'for heavy vehicles only', 
             'for cars and light vehicles only', 
             'snowploughs in use', 
             'gritting vehicles in use', 
             'drive carefully', 
             'keep your distance', 
             'observe signals', 
             'overtake with care', 
             'cross junction with care', 
             'no overtaking', 
             'use headlights', 
             'use fog lights', 
             'do not leave your vehicle', 
             'switch off engine', 
             'close all windows. Turn off heater and vents', 
             'test your brakes', 
             'winter equipment recommended', 
             'snow chains recommended', 
             'snow chains mandatory', 
             'keep to the left', 
             'keep to the right', 
             'use hard shoulder as lane', 
             'do not drive on the hard shoulder', 
             'in the opposite direction', 
             'in the opposing lanes', 
             'in the overtaking lane', 
             'in the crawler lane', 
             'in the right lane', 
             'in the middle lane', 
             'in the left lane', 
             'on the roadway', 
             'police directing traffic', 
             'police in attendance', 
             'extra police patrols in operation', 
             'rescue and recovery work in progress', 
             'look out for flagman', 
             'why not park-and-ride?', 
             'why not try public transport?', 
             'only travel if absolutely necessary', 
             'increased risk of accident', 
             'on bridges', 
             'in shaded areas', 
             'entering or leaving tunnels', 
             'winter closure', 
             'batch service in progress', 
             'the north', 
             'the north-east', 
             'the east', 
             'the south-east', 
             'the south', 
             'the south-west', 
             'the west', 
             'the north-west', 
             'follow special diversion markers', 
             'do not follow diversion signs', 
             'follow local diversion', 
             'compulsory diversion in operation', 
             'for petrol-engined vehicles only', 
             'for diesel-engined vehicles only', 
             'for LPG vehicles only', 
             'local drivers are recommended to avoid the area', 
             'for 4-wheel-drive with snow tyres or chains only', 
             'in the median', 
             'for cars only', 
             'for light vehicles only', 
             'for vehicles with catalytic converters', 
             'for vehicles without catalytic converters', 
             'for cars with trailers only', 
             'for cars with caravans only', 
             'for vehicles with trailers only', 
             'for heavy lorries only', 
             'for buses only', 
             'for articulated vehicles only', 
             'for high-sided vehicles only', 
             'for hazardous loads only', 
             'for abnormal loads only', 
             'with even-numbered registration plates', 
             'with odd-numbered registration plates', 
             'for all vehicles', 
             'for through traffic', 
             'for rail services', 
             'on the underground', 
             'danger', 
             'repairs in progress', 
             'pilot car in operation', 
             'emergency vehicles at scene', 
             'traffic being directed around accident area', 
             'danger of explosion', 
             'danger of fire', 
             'radiation hazard', 
             'toxic leak', 
             'firemen directing traffic', 
             'police speed checks in operation', 
             'mandatory speed limit in force', 
             'speed limit in force for heavy vehicles', 
             'reduce your speed', 
             'observe speed limits', 
             'observe recommended speed', 
             'snow chains required', 
             'snow chains or tyres reqired', 
             'helicopter rescue in progress', 
             'several accidents have taken place', 
             'drive with extreme caution', 
             'approach with care', 
             'increase normal following distance', 
             'do not allow unnecessary gaps', 
             'follow the vehicle in front, smoothly', 
             'do not slow down unneccessarily', 
             'observe signs', 
             'use hazard warning lights', 
             'no smoking', 
             'no naked flames', 
             'switch off mobile phones and two-way radios', 
             'allow emergency vehicles to pass', 
             'clear a lane for emergency vehicles', 
             'pull over to the edge of the roadway', 
             'wait for escort vehicle', 
             'in emergency, wait for police patrol', 
             'stop at next safe place', 
             'clear a lane for snowploughs and gritting vehicles', 
             'use right lane', 
             'use left lane', 
             'heavy vehicles use right lane', 
             'heavy vehicles use left lane', 
             'stop at next service area', 
             'on the right', 
             'in the centre', 
             'on the left', 
             'in the bus lane', 
             'in the carpool lane', 
             'on the hard shoulder', 
             'in the emergency lane', 
             'on the opposite carriageway', 
             'in the heavy vehicle lane', 
             'in the local lane', 
             'due to heat', 
             'due to frost', 
             'for ferry service', 
             'for roads in', 
             'in the through traffic lane', 
             'in the express lane', 
             'in the connecting carriageway', 
             'in the parallel carriageway', 
             'in the right-hand parallel carriageway', 
             'in the left-hand parallel carriageway', 
             'in tunnels', 
             'on slip roads', 
             'at high altitudes', 
             'in low-lying areas', 
             'around a bend in the road', 
             'over the crest of a hill', 
             'in the city centre', 
             'in the inner city area', 
             'in the slow vehicle lane', 
             'in the turning lane', 
             'due to an earlier accident', 
             'due to shear weight of traffic', 
             'due to large numbers of visitors', 
             'due to holiday traffic', 
             'due to technical problems', 
             'towards town', 
             'from town', 
             'on entry into the country', 
             'on leaving the country', 
             'do not throw out any burning objects', 
             'traffic wardens directing traffic', 
             'due to falling ice', 
             'snow tyres recommended', 
             'snow tyres mandatory', 
             'use through traffic lanes', 
             'use local traffic lanes', 
             'use left-hand parallel carriageway', 
             'use right-hand parallel carriageway', 
             'use heavy vehicle lane', 
             'due to an earlier incident', 
             'why not ride share?', 
             'is this your no-ride day?', 
             'due to an earlier event', 
             'please use rail service', 
             'please use underground service', 
             'please use tram service', 
             'please use bus service', 
             'for a limited time', 
             'your parking ticket covers the return ride', 
             'avoid the rush hour', 
             'for holiday traffic', 
             'for residents', 
             'several times', 
             'during the day time', 
             'during off-peak periods', 
             'during the night', 
             'until further notice', 
             'for arrivals', 
             'for departures', 
             'access only', 
             'only', 
             'except', 
             'for long distance traffic', 
             'for local traffic', 
             'for regional traffic', 
             'unconfirmed report', 
             'on manual payment lanes', 
             'sorry for any delay', 
             'for roads leading towards', 
             'for roads from', 
             'we are grateful for your cooperation', 
             'Traffic queue length decreasing at an average rate of 10 km/hr', 
             'Traffic queue length decreasing at an average rate of 20 km/hr', 
             'Traffic queue length decreasing at an average rate of 30 km/hr', 
             'Traffic queue length decreasing at an average rate of 40 km/hr', 
             'leave your vehicle. Proceed to next save place', 
             'for visitors', 
             'in the roadworks area', 
             'from', 
             'to', 
             'in', 
             'Traffic queue length increasing', 
             'Traffic queue length increasing at an average rate of 10 km/hr', 
             'Traffic queue length increasing at an average rate of 20 km/hr', 
             'Traffic queue length increasing at an average rate of 30 km/hr', 
             'Traffic queue length increasing at an average rate of 40 km/hr', 
             'very frequent service', 
             'frequent service', 
             'fairly frequent service', 
             'regular service', 
             'Traffic queue length decreasing']

__all__ = ["TMC_CODES"]


if __name__ == "__main__":
    import csv

    def create_tmc_constant(tmc_file="tmc.csv"):

        with open(tmc_file, "r") as f:
            reader = csv.reader(f)
            header = next(reader)
            data = ["NaN"]
            for row in reader:
                data.append(row[1])
        return data
